apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  externalIPs: ["192.168.0.15","192.168.0.4"]
  ports:
  - name: http
    port: 8001
    targetPort: http
